name: Sync

on:
  schedule:
    - cron: 0 0 * * *

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
            path: repo
      - name: Checkout upstream repo
        uses: actions/checkout@v3
        with:
            repository: daniel-stoneuk/extensions
            path: upstream
      - name: Update mirror
        run: |
          rm -rf repo/gitignore
          cp -r upstream/extensions/gitignore repo/gitignore
          cd repo
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff-index --quiet HEAD || git commit -m "Merging latest changes"
          git push
